insert into public.lessons(topic_id,title,explanation,example,status) select t.id,'Equações: mantenha os dois lados em equilíbrio','Uma equação compara duas expressões iguais. Para descobrir a incógnita, faça a mesma operação dos dois lados. Isso preserva a igualdade.','Em 3x + 6 = 21, subtraia 6 dos dois lados: 3x = 15. Depois divida os dois lados por 3: x = 5.','published' from public.topics t join public.subjects s on s.id=t.subject_id where s.slug='matematica' on conflict(topic_id,title) do nothing;
with a as(insert into public.learning_activities(lesson_id,kind,prompt,difficulty,position,status) select id,'NUMERIC_INPUT','Resolva: 4x + 8 = 28. Digite o valor de x.',4,0,'published' from public.lessons l where title='Equações: mantenha os dois lados em equilíbrio' and not exists(select 1 from public.learning_activities x where x.lesson_id=l.id and x.position=0) returning id) insert into private.activity_keys select id,'{"value":5,"tolerance":0.001}'::jsonb,'Subtraia 8: 4x = 20. Divida por 4: x = 5.' from a;
with a as(insert into public.learning_activities(lesson_id,kind,prompt,difficulty,position,status) select id,'TRUE_FALSE','Subtrair o mesmo número dos dois lados mantém a igualdade.',4,1,'published' from public.lessons l where title='Equações: mantenha os dois lados em equilíbrio' and not exists(select 1 from public.learning_activities x where x.lesson_id=l.id and x.position=1) returning id) insert into private.activity_keys select id,'{"value":true,"tolerance":0.001}'::jsonb,'A afirmação corresponde ao conceito apresentado.' from a;
insert into public.lessons(topic_id,title,explanation,example,status) select t.id,'Encontre o núcleo do sujeito','O sujeito é o termo sobre o qual se faz uma afirmação. Seu núcleo é a palavra central, geralmente um substantivo ou pronome. Artigos e adjetivos podem acompanhar esse núcleo.','Em “Os alunos atentos chegaram”, o sujeito é “Os alunos atentos”. O núcleo é “alunos”.','published' from public.topics t join public.subjects s on s.id=t.subject_id where s.slug='portugues' on conflict(topic_id,title) do nothing;
with a as(insert into public.learning_activities(lesson_id,kind,prompt,difficulty,position,status) select id,'FILL_BLANK','Complete com uma palavra: em “As meninas chegaram cedo”, o núcleo do sujeito é ____.',4,0,'published' from public.lessons l where title='Encontre o núcleo do sujeito' and not exists(select 1 from public.learning_activities x where x.lesson_id=l.id and x.position=0) returning id) insert into private.activity_keys select id,'{"value":"meninas","tolerance":0.001}'::jsonb,'“Meninas” é o substantivo central. “As” é artigo e “cedo” indica circunstância de tempo.' from a;
with a as(insert into public.learning_activities(lesson_id,kind,prompt,difficulty,position,status) select id,'TRUE_FALSE','Em “Os alunos chegaram”, o núcleo do sujeito é “Os”.',4,1,'published' from public.lessons l where title='Encontre o núcleo do sujeito' and not exists(select 1 from public.learning_activities x where x.lesson_id=l.id and x.position=1) returning id) insert into private.activity_keys select id,'{"value":false,"tolerance":0.001}'::jsonb,'Releia o conceito: a afirmação altera uma parte importante da explicação.' from a;
insert into public.lessons(topic_id,title,explanation,example,status) select t.id,'Força, massa e aceleração','A força resultante determina como a velocidade muda. Na segunda lei de Newton, F = m × a. Para uma mesma força, um corpo com maior massa terá menor aceleração.','Se uma força de 12 N atua em 3 kg, a = F/m = 12/3 = 4 m/s².','published' from public.topics t join public.subjects s on s.id=t.subject_id where s.slug='fisica' on conflict(topic_id,title) do nothing;
with a as(insert into public.learning_activities(lesson_id,kind,prompt,difficulty,position,status) select id,'NUMERIC_INPUT','Uma força resultante de 20 N atua em 5 kg. Qual é a aceleração, em m/s²?',4,0,'published' from public.lessons l where title='Força, massa e aceleração' and not exists(select 1 from public.learning_activities x where x.lesson_id=l.id and x.position=0) returning id) insert into private.activity_keys select id,'{"value":4,"tolerance":0.001}'::jsonb,'Divida a força pela massa: 20/5 = 4 m/s².' from a;
with a as(insert into public.learning_activities(lesson_id,kind,prompt,difficulty,position,status) select id,'TRUE_FALSE','Mantendo a força resultante, dobrar a massa reduz a aceleração pela metade.',4,1,'published' from public.lessons l where title='Força, massa e aceleração' and not exists(select 1 from public.learning_activities x where x.lesson_id=l.id and x.position=1) returning id) insert into private.activity_keys select id,'{"value":true,"tolerance":0.001}'::jsonb,'A afirmação corresponde ao conceito apresentado.' from a;
insert into public.lessons(topic_id,title,explanation,example,status) select t.id,'Concentração: quanto há em cada litro?','A concentração comum relaciona a massa de soluto ao volume total da solução: C = m/V. Antes de dividir, converta o volume para a unidade pedida.','10 g em 500 mL: 500 mL = 0,5 L. Assim, C = 10/0,5 = 20 g/L.','published' from public.topics t join public.subjects s on s.id=t.subject_id where s.slug='quimica' on conflict(topic_id,title) do nothing;
with a as(insert into public.learning_activities(lesson_id,kind,prompt,difficulty,position,status) select id,'NUMERIC_INPUT','Uma solução tem 6 g de soluto em 300 mL. Qual é a concentração em g/L?',4,0,'published' from public.lessons l where title='Concentração: quanto há em cada litro?' and not exists(select 1 from public.learning_activities x where x.lesson_id=l.id and x.position=0) returning id) insert into private.activity_keys select id,'{"value":20,"tolerance":0.001}'::jsonb,'300 mL são 0,3 L. Logo, 6/0,3 = 20 g/L.' from a;
with a as(insert into public.learning_activities(lesson_id,kind,prompt,difficulty,position,status) select id,'TRUE_FALSE','Para calcular concentração em g/L, podemos usar mililitros diretamente sem converter.',4,1,'published' from public.lessons l where title='Concentração: quanto há em cada litro?' and not exists(select 1 from public.learning_activities x where x.lesson_id=l.id and x.position=1) returning id) insert into private.activity_keys select id,'{"value":false,"tolerance":0.001}'::jsonb,'Releia o conceito: a afirmação altera uma parte importante da explicação.' from a;
insert into public.lessons(topic_id,title,explanation,example,status) select t.id,'Da informação à proteína','Ribossomos participam da síntese de proteínas. Eles leem a informação do RNA mensageiro e unem aminoácidos na sequência indicada.','Pense no RNA mensageiro como uma sequência de instruções. O ribossomo acompanha essa sequência para montar uma cadeia de aminoácidos.','published' from public.topics t join public.subjects s on s.id=t.subject_id where s.slug='biologia' on conflict(topic_id,title) do nothing;
with a as(insert into public.learning_activities(lesson_id,kind,prompt,difficulty,position,status) select id,'FILL_BLANK','Complete com uma palavra: a organela que participa diretamente da síntese de proteínas é o ____.',4,0,'published' from public.lessons l where title='Da informação à proteína' and not exists(select 1 from public.learning_activities x where x.lesson_id=l.id and x.position=0) returning id) insert into private.activity_keys select id,'{"value":"ribossomo","tolerance":0.001}'::jsonb,'O ribossomo traduz a informação do RNA mensageiro em uma sequência de aminoácidos.' from a;
with a as(insert into public.learning_activities(lesson_id,kind,prompt,difficulty,position,status) select id,'TRUE_FALSE','Ribossomos participam da montagem de proteínas a partir de aminoácidos.',4,1,'published' from public.lessons l where title='Da informação à proteína' and not exists(select 1 from public.learning_activities x where x.lesson_id=l.id and x.position=1) returning id) insert into private.activity_keys select id,'{"value":true,"tolerance":0.001}'::jsonb,'A afirmação corresponde ao conceito apresentado.' from a;
insert into public.lessons(topic_id,title,explanation,example,status) select t.id,'Uma fonte tem contexto','Fontes históricas são registros produzidos por pessoas em situações específicas. Perguntar quem produziu, quando e com qual finalidade ajuda a interpretar o registro.','Uma propaganda política revela discursos e interesses de quem a produziu. Ela não deve ser tratada como descrição neutra de toda a sociedade.','published' from public.topics t join public.subjects s on s.id=t.subject_id where s.slug='historia' on conflict(topic_id,title) do nothing;
with a as(insert into public.learning_activities(lesson_id,kind,prompt,difficulty,position,status) select id,'FILL_BLANK','Complete: autoria, finalidade e situação de produção ajudam a compreender o ____ de uma fonte.',4,0,'published' from public.lessons l where title='Uma fonte tem contexto' and not exists(select 1 from public.learning_activities x where x.lesson_id=l.id and x.position=0) returning id) insert into private.activity_keys select id,'{"value":"contexto","tolerance":0.001}'::jsonb,'O contexto conecta a fonte à situação histórica em que foi produzida.' from a;
with a as(insert into public.learning_activities(lesson_id,kind,prompt,difficulty,position,status) select id,'TRUE_FALSE','Toda fonte histórica descreve os acontecimentos de forma neutra.',4,1,'published' from public.lessons l where title='Uma fonte tem contexto' and not exists(select 1 from public.learning_activities x where x.lesson_id=l.id and x.position=1) returning id) insert into private.activity_keys select id,'{"value":false,"tolerance":0.001}'::jsonb,'Releia o conceito: a afirmação altera uma parte importante da explicação.' from a;
insert into public.lessons(topic_id,title,explanation,example,status) select t.id,'Escala: do mapa ao espaço','A escala expressa a relação entre uma distância no mapa e a correspondente distância real, usando a mesma unidade. Em 1:100.000, 1 cm representa 100.000 cm.','100.000 cm equivalem a 1.000 m, ou 1 km. Portanto, 2 cm nesse mapa representam 2 km.','published' from public.topics t join public.subjects s on s.id=t.subject_id where s.slug='geografia' on conflict(topic_id,title) do nothing;
with a as(insert into public.learning_activities(lesson_id,kind,prompt,difficulty,position,status) select id,'NUMERIC_INPUT','Em escala 1:50.000, uma distância de 4 cm representa quantos quilômetros?',4,0,'published' from public.lessons l where title='Escala: do mapa ao espaço' and not exists(select 1 from public.learning_activities x where x.lesson_id=l.id and x.position=0) returning id) insert into private.activity_keys select id,'{"value":2,"tolerance":0.001}'::jsonb,'4 × 50.000 = 200.000 cm = 2.000 m = 2 km.' from a;
with a as(insert into public.learning_activities(lesson_id,kind,prompt,difficulty,position,status) select id,'TRUE_FALSE','Escala 1:100.000 significa que 1 cm no mapa representa 1 km no espaço real.',4,1,'published' from public.lessons l where title='Escala: do mapa ao espaço' and not exists(select 1 from public.learning_activities x where x.lesson_id=l.id and x.position=1) returning id) insert into private.activity_keys select id,'{"value":true,"tolerance":0.001}'::jsonb,'A afirmação corresponde ao conceito apresentado.' from a;
with a as (
 insert into public.learning_activities(lesson_id,kind,prompt,payload,difficulty,position,status)
 select id,'ORDERING','Organize os passos para resolver 2x + 6 = 14.',
 '{"items":["x = 4","2x + 6 = 14","2x = 8"]}'::jsonb,3,2,'published'
 from public.lessons l where title='Equações: mantenha os dois lados em equilíbrio'
 and not exists(select 1 from public.learning_activities x where x.lesson_id=l.id and x.position=2)
 returning id
) insert into private.activity_keys select id,'{"value":["2x + 6 = 14","2x = 8","x = 4"]}'::jsonb,
 'Parta da equação original. Subtraia 6 dos dois lados e, depois, divida ambos por 2.' from a;
