import Link from 'next/link';
import { ArrowUpRight, ArrowRight, Sparkles, Focus, RotateCcw, Check, MoveUpRight } from 'lucide-react';
import { Logo } from '@/components/logo';
import { brand } from '@/config/brand';
export default function Landing() {
  return <div className="landing"><header className="public-header wrap"><Logo/><nav aria-label="Navegação pública"><Link href="/entrar">Entrar</Link><Link href="/cadastro" className="button small dark">Começar <ArrowUpRight size={16}/></Link></nav></header>
    <main id="main"><section className="hero wrap"><div className="hero-copy"><span className="eyebrow"><span className="live-dot"/> SEU PRÓXIMO NÍVEL COMEÇA AQUI</span><h1>Seu ritmo.<br/>Seu caminho.<br/><span>Seu próximo nível.</span></h1><p>Você não precisa estudar tudo de novo.<br className="desktop-break"/> Precisa descobrir o que vem a seguir.</p><Link className="button primary" href="/cadastro">Começar gratuitamente <ArrowRight size={19}/></Link><div className="hero-note">Sem cartão de crédito. Um passo de cada vez.</div></div>
    <div className="hero-art" aria-label="Ilustração do caminho de aprendizado"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><span className="art-label">CONHECIMENTO EM MOVIMENTO</span><div className="art-core"><span>n</span><i/></div><div className="floating-card card-top"><span className="mini-icon"><Focus size={20}/></span><div><b>O desafio certo.</b><small>Na hora certa para você.</small></div></div><div className="floating-card card-bottom"><div className="mini-bars"><i/><i/><i/><i/><i/></div><div><b>Cada passo conta.</b><small>Seu progresso, mais claro.</small></div><MoveUpRight size={20}/></div><span className="art-coordinate">01 / INFINITAS POSSIBILIDADES</span></div></section>
    <section className="manifesto wrap"><span className="eyebrow">MENOS RUÍDO. MAIS APRENDIZADO.</span><h2>Estudar faz mais sentido<br/>quando faz sentido para você.</h2><div className="feature-grid"><article><Focus/><h3>Um desafio do seu tamanho</h3><p>Questões que se adaptam ao seu conhecimento, sem pular etapas nem prender você no básico.</p></article><article><RotateCcw/><h3>O que importa, na memória</h3><p>Seus erros viram oportunidades. Revisite os assuntos no momento de consolidar o aprendizado.</p></article><article><Sparkles/><h3>Clareza em cada passo</h3><p>Acompanhe seus pontos fortes, pratique com simulados e saiba onde concentrar sua energia.</p></article></div></section>
    <section className="cta wrap"><div><span className="eyebrow">COMECE DE ONDE VOCÊ ESTÁ</span><h2>{brand.slogan}</h2><p><Check size={16}/> Questões · Simulados · Progresso</p></div><Link href="/cadastro" className="button primary">Encontrar meu próximo nível <ArrowRight size={18}/></Link></section></main><footer className="wrap public-footer"><Logo/><span>Conhecimento que conecta.</span><Link href="/privacidade">Privacidade</Link></footer></div>;
}
