import {content} from './original-question-content.mjs';
// Authored support for the original 42 questions, aligned with their option order.
// These are stored editorial explanations, never fabricated runtime AI responses.
const support={
 matematica:[
 ['Desfaça primeiro a adição, mantendo a igualdade nos dois lados.','Operações inversas em equações de primeiro grau.',['3 × 3 + 6 = 15, diferente de 21.','3 × 5 + 6 = 21: a igualdade é satisfeita.','Dividir 21 por 3 antes de retirar o 6 ignora uma parcela.','3 × 9 + 6 = 33, diferente de 21.']],
 ['Calcule a parte correspondente ao desconto antes de subtraí-la do preço.','Porcentagem como fração de uma quantidade.',['Desconto de R$ 50 corresponde a 25%, não a 15%.','Desconto de R$ 35 corresponde a 17,5%.','O desconto é 0,15 × 200 = 30; o preço fica 170.','Subtrair 15 reais confunde porcentagem com valor monetário.']],
 ['Busque dois números cujo produto e soma permitam fatorar o polinômio.','Fatoração e propriedade do produto nulo.',['1 e 6 têm produto 6, mas soma 7; não geram o coeficiente −5.','(x − 2)(x − 3) reproduz o polinômio.','Raízes negativas gerariam o termo +5x.','Além dos sinais, a soma −7 não corresponde à soma das raízes.']],
 ['Use a propriedade da soma de logaritmos e confira o domínio ao final.','Logaritmo de um produto e domínio de funções logarítmicas.',['Para x = 2, o produto (x − 1)(x + 1) é 3, não 8.','x² − 1 = 8 fornece x = ±3; o domínio permite apenas 3.','Para x = 4, o produto vale 15.','O valor 8 é o argumento após converter o logaritmo; ainda não é x.']],
 ['Conte quantos saltos separam o primeiro termo do décimo.','Termo geral de uma progressão aritmética.',['27 é apenas 9 vezes a razão; falta somar o primeiro termo.','28 não resulta de somar nove razões a 4.','Usar dez razões confunde posição com número de intervalos.','Há nove intervalos: 4 + 9 × 3 = 31.']],
 ['Transforme o módulo em uma desigualdade dupla e respeite os extremos abertos.','Inequação modular e contagem de números inteiros.',['Excluir também o zero deixa um inteiro válido de fora.','Os valores 0, 1, 2 e 3 satisfazem a desigualdade estrita.','Incluir um dos extremos −1 ou 4 viola o sinal de menor estrito.','Incluir ambos os extremos viola a desigualdade.']],
 ],
 portugues:[
 ['Encontre quem pratica a ação e identifique a palavra central desse grupo.','Núcleo nominal do sujeito.',['“As” é artigo que acompanha o núcleo.','“Meninas” é o substantivo central do sujeito.','“Chegaram” é o verbo do predicado.','“Cedo” indica circunstância de tempo.']],
 ['Compare o sentido literal com uma imagem usada para expressar uma sensação.','Linguagem denotativa e conotativa.',['O horário de chegada está em sentido literal.','A fervura é descrita literalmente.','O sorriso não emite luz: “iluminou” expressa uma sensação.','A quantidade de páginas está em sentido literal.']],
 ['Verifique se há encontro de preposição a com artigo feminino a.','Crase depende de regência e presença do artigo.',['“Pé” é masculino; a expressão é “a pé”.','Entregar a alguém + a professora resulta em “à professora”.','“Tempo” é masculino: “a tempo”.','Antes de verbo no infinitivo não há artigo feminino: “a estudar”.']],
 ['Pense se a chuva causa a saída ou se é um obstáculo que não a impediu.','Relação de concessão entre orações.',['A saída não é apresentada como causada pela chuva.','Chover não é a finalidade da saída.','A ação ocorre apesar do obstáculo: concessão.','A chuva não aparece como consequência da saída.']],
 ['Diferencie verbos impessoais daqueles que concordam com um sujeito plural.','Concordância verbal e impessoalidade.',['“Fazer” indicando tempo decorrido fica no singular: faz dois anos.','“Haver” com sentido de existir fica no singular: houve candidatos.','“Existir” tem sujeito plural e concorda com oportunidades.','No tempo composto, o auxiliar concorda: haviam chegado os alunos.']],
 ['Tente reescrever a frase usando o verbo ser seguido de particípio.','Voz passiva sintética e sujeito paciente.',['O sujeito é identificável: livros usados.','A frase equivale a “Livros usados são vendidos”.','Os livros não praticam sobre si mesmos a ação de vender.','O “se” não introduz uma oração subordinada substantiva.']],
 ],
 fisica:[
 ['Relacione a distância total ao tempo total, cuidando das unidades.','Taxa média de deslocamento na situação apresentada.',['30 km/h corresponderia a percorrer 60 km em 2 h.','120 ÷ 2 = 60 km/h.','90 km/h durante 2 h daria 180 km.','Multiplicar distância por tempo não calcula velocidade média.']],
 ['Isole a aceleração na relação entre força resultante e massa.','Segunda lei de Newton: F = m a.',['3 é o valor da massa, não da aceleração.','a = 12 ÷ 3 = 4 m/s².','Subtrair massa de força mistura grandezas incompatíveis.','Multiplicar força por massa não isola a aceleração.']],
 ['Identifique massa, gravidade e altura; a energia depende das três grandezas.','Energia potencial gravitacional próxima à superfície terrestre.',['O valor 10 não inclui os três fatores m, g e h.','Elevar a altura ao quadrado não faz parte de mgh.','50 corresponde a gh; falta multiplicar pela massa.','2 × 10 × 5 = 100 J.']],
 ['Partida do repouso elimina o termo da velocidade inicial; lembre que o tempo aparece ao quadrado.','Deslocamento no movimento uniformemente acelerado.',['a × t calcula a variação de velocidade, não o deslocamento.','18 deixa de considerar corretamente a aceleração de 2 m/s².','Δs = 2 × 6² ÷ 2 = 36 m.','72 omite a divisão por 2.']],
 ['Na lei de Ohm, isole a corrente e verifique a ordem da divisão.','Lei de Ohm: tensão = resistência × corrente.',['0,5 resulta da divisão inversa, R/V.','12 ÷ 6 = 2 A.','6 é a resistência, não a corrente.','Multiplicar V por R não calcula a corrente.']],
 ['Some os momentos antes da colisão e use a massa total depois dela.','Conservação do momento linear em colisão perfeitamente inelástica.',['2 m/s daria momento final menor que o inicial.','8m = 2m v, portanto v = 4 m/s.','Manter 8 m/s dobraria o momento porque a massa final dobra.','16 m/s aumentaria ainda mais o momento sem força externa.']],
 ],
 quimica:[
 ['Compare os sinais das cargas das três partículas subatômicas mais comuns.','Cargas elétricas de prótons, nêutrons e elétrons.',['O próton tem carga positiva.','O nêutron é eletricamente neutro.','O elétron tem carga negativa.','O núcleo reúne prótons e nêutrons; sua carga é positiva.']],
 ['Um filtro simples retém partículas de sólido insolúvel, mas não soluto dissolvido.','Separação de mistura heterogênea sólido-líquido.',['O sal dissolvido atravessa o filtro com a água.','A areia insolúvel é retida; a água atravessa o filtro.','Água e álcool são líquidos miscíveis; filtração simples não os separa.','Uma mistura de gases não é separada por esse processo.']],
 ['Converta o volume para litros antes de dividir a massa do soluto pelo volume da solução.','Concentração comum: C = m/V.',['Multiplicar 10 por 0,5 não calcula concentração.','10 g/L desconsidera que o volume é meio litro.','500 mL = 0,5 L; 10/0,5 = 20 g/L.','50 g/L corresponderia a 10 g em 0,2 L.']],
 ['Compare apenas os coeficientes do hidrogênio e da água; o oxigênio está em excesso.','Proporção em mols dada pelos coeficientes estequiométricos.',['1 mol não preserva a relação 2:2 entre H₂ e H₂O.','Dividir por 2 confunde a proporção H₂:O₂ com H₂:H₂O.','A razão H₂:H₂O é 1:1, formando 3 mols de água.','Multiplicar por 2 ignora que o reagente também tem coeficiente 2.']],
 ['Compare o pH informado com o valor de neutralidade nessa temperatura.','Classificação ácido-base pelo pH a 25 °C.',['pH 3 é menor que 7: solução ácida.','Neutralidade corresponde a pH 7 nessa temperatura.','Solução básica tem pH maior que 7 a 25 °C.','pH não determina se a solução está saturada.']],
 ['Considere uma compressão a temperatura constante e compare os coeficientes dos gases nos dois lados.','Resposta do equilíbrio gasoso à compressão, pelo princípio de Le Chatelier.',['Mais mols de gás não se opõem à compressão.','Quando os lados têm quantidades gasosas diferentes, a compressão favorece o lado com menos mols.','O critério é o número de mols gasosos, não a massa molar.','A questão trata de pressão; não há aumento obrigatório de temperatura.']],
 ],
 biologia:[
 ['Pense na estrutura que lê o RNA mensageiro e reúne aminoácidos.','Tradução e síntese proteica.',['Ribossomos participam diretamente da tradução.','Lisossomos atuam principalmente na digestão intracelular.','Centríolos participam da organização de microtúbulos.','Vacúolos têm funções como armazenamento e regulação osmótica.']],
 ['Considere em que forma a energia fica armazenada nos compostos orgânicos produzidos.','Transformação de energia na fotossíntese.',['Fotossíntese não é uma reação nuclear.','Os compostos orgânicos armazenam energia química.','A produção de som não é o principal resultado energético.','Não há conversão principal em energia de posição gravitacional.']],
 ['Monte as combinações dos gametas A e a de cada progenitor.','Segregação de alelos em um cruzamento monohíbrido.',['Cada progenitor pode fornecer a; o genótipo aa é possível.','Um dos quatro resultados do quadro de Punnett é aa.','50% corresponde aos heterozigotos, não a aa.','75% pode representar o fenótipo dominante sob dominância completa, não o genótipo aa.']],
 ['Observe que o enunciado destaca um evento aleatório, não uma vantagem adaptativa.','Efeito gargalo e amostragem aleatória de alelos.',['O efeito gargalo é um caso de deriva genética.','Mutações não surgem dirigidas pela necessidade da população.','Uso e desuso não explica amostragem aleatória de alelos.','Não há escolha humana de indivíduos reprodutores na situação.']],
 ['Procure quem produz matéria orgânica a partir de uma fonte externa de energia.','Fluxo de energia e níveis tróficos.',['Decompositores usam matéria orgânica já produzida.','Consumidores secundários obtêm energia de outros seres vivos.','Produtores incorporam energia externa à matéria orgânica.','Parasitas dependem de um hospedeiro, não cumprem essa função geral.']],
 ['Aplique o pareamento de bases e mantenha as duas fitas em sentidos opostos.','Complementaridade e antiparalelismo do DNA.',['As bases complementam, mas o sentido indicado é paralelo.','A–T e G–C, em sentido antiparalelo: 3′-TACG-5′.','A sequência foi repetida, sem complementar as bases.','Uracila é própria do RNA; além disso, a orientação está incorreta.']],
 ],
 historia:[
 ['Diferencie a abolição geral das leis anteriores que tiveram alcance parcial.','Processo histórico de abolição legal da escravidão no Brasil.',['A Lei Áurea, de 1888, aboliu legalmente a escravidão.','A Lei de Terras trata do acesso à propriedade da terra.','Leis de cotas não são a lei abolicionista de 1888.','A Lei do Ventre Livre, de 1871, teve alcance parcial e anterior.']],
 ['Compare a produção artesanal com mudanças técnicas e na organização do trabalho.','Mecanização e sistema fabril na Revolução Industrial.',['O movimento central foi ampliar a mecanização, não retornar ao artesanato.','Máquinas e fábricas transformaram a produção e o trabalho.','A industrialização favoreceu o crescimento urbano, não o fim das cidades.','A energia a vapor teve papel importante na industrialização.']],
 ['Relacione o movimento à crítica da autoridade e à valorização da investigação racional.','Razão, crítica e direitos no pensamento iluminista.',['A defesa irrestrita do absolutismo contraria críticas iluministas ao poder arbitrário.','Razão e crítica aos privilégios são aspectos centrais do movimento.','A investigação científica foi valorizada, não rejeitada por completo.','Restaurar o feudalismo não era seu objetivo central.']],
 ['Relacione o texto constitucional à ampliação de direitos e à participação política.','Direitos e redemocratização na Constituição de 1988.',['A Constituição assegurou participação eleitoral, não extinguiu eleições diretas.','O texto ampliou direitos e garantias democráticas.','A forma republicana foi mantida.','A liberdade de associação foi garantida, não proibida em geral.']],
 ['Pense nos polos de poder que se consolidaram após a Segunda Guerra Mundial.','Bipolaridade e disputas políticas da Guerra Fria.',['A rivalidade colonial ibérica pertence a outro contexto histórico.','Estados Unidos e União Soviética lideraram os principais blocos rivais.','Brasil e Argentina não eram os dois polos da Guerra Fria.','França e Itália não formaram os dois blocos centrais desse conflito.']],
 ['Considere quem produziu a fonte, em que momento, para quem e com qual finalidade.','Análise crítica de fontes históricas.',['Fontes têm perspectivas e limites; sua neutralidade não pode ser presumida.','O contexto ajuda a avaliar interesses, perspectivas e limites.','Autoria é parte importante da análise, não deve ser ignorada.','A análise contextual qualifica as evidências; não as substitui por opinião.']],
 ],
 geografia:[
 ['Procure a linha de latitude zero, e não um meridiano.','Paralelos, meridianos e hemisférios terrestres.',['O Trópico de Capricórnio está no hemisfério Sul.','Greenwich é referência de longitude, não a divisão Norte–Sul.','O Equador tem latitude zero e separa Norte e Sul.','O Círculo Polar Ártico fica no hemisfério Norte.']],
 ['Multiplique a distância do mapa pelo denominador da escala e só então converta a unidade.','Escala cartográfica e conversão de centímetros em quilômetros.',['200 m corresponde a 20.000 cm; falta um fator 10.','1 km corresponde a apenas 1 cm nessa escala.','2 × 100.000 cm = 200.000 cm = 2 km.','20 km acrescenta um fator 10 indevido na conversão.']],
 ['Observe que importa a participação da população urbana no total, não só o crescimento de uma cidade.','Urbanização como transformação da distribuição populacional.',['Urbanização é o aumento da proporção de habitantes em áreas urbanas.','Desertificação envolve degradação de terras em regiões secas.','Intemperismo envolve alteração e desagregação de rochas.','Sedimentação é a deposição de materiais transportados.']],
 ['Compare a retenção de calor dos materiais urbanos com o efeito da vegetação.','Balanço térmico e ilhas de calor urbanas.',['Vegetação e evapotranspiração tendem a amenizar o aquecimento.','Materiais urbanos e impermeabilização favorecem retenção de calor.','Reduzir construções não é a causa principal apontada para ilhas de calor.','Atividades humanas participam do fenômeno urbano.']],
 ['Considere o tempo de reposição da fonte em comparação com a escala de uso humano.','Fontes renováveis e combustíveis fósseis.',['Carvão mineral se forma em escala geológica e é finito.','Petróleo é combustível fóssil não renovável em escala humana.','Gás natural também é uma fonte fóssil finita.','A radiação solar é continuamente recebida em escala humana.']],
 ['Relacione a base às faixas etárias jovens e o topo às mais idosas.','Estrutura etária e transição demográfica.',['Alta natalidade recente tenderia a ampliar a base, não estreitá-la.','Menor base e maior proporção idosa indicam menor natalidade e envelhecimento.','O padrão é compatível com fases avançadas da transição demográfica.','O crescimento natural não precisa ser elevado nesse padrão.']],
 ]
};
export const pedagogyContent=content.flatMap(([,slug,,questions])=>questions.map(([,statement,options,answer,explanation],i)=>{
 const [hint,key_concept,option_explanations]=support[slug][i];
 return {statement,hint,key_concept,
  solution_steps:explanation.split(/(?<=[.!?])\s+/u).filter(Boolean),
  option_explanations:option_explanations||options.map((option,index)=>index===answer?`Correta. ${explanation}`:`“${option}” não corresponde ao fenômeno descrito. ${explanation}`),
  common_mistakes:[slug==='matematica'||slug==='fisica'||slug==='quimica'?'Aplicar uma operação sem verificar a relação entre as grandezas e as condições do enunciado.':'Escolher por uma palavra isolada, sem relacionar a alternativa ao contexto do enunciado.'],
  prerequisites:[key_concept],skills:['Interpretar o enunciado','Justificar a escolha'],
 };
}));
